.TH achilterm "1" "August 2013" "achilterm 0.1" "User commands"
.SH NAME
achilterm \- Web based terminal written in python

.SH DESCRITPION
\fBachilterm\fR is a web based terminal written in python and some AJAX
javascript for client side.
It can use almost any web browser and even works through firewalls.

.SH USAGE
\fBachilterm\fR [options]

.SH OPTIONS
A summary of the options supported by \fBachilterm\fR is included below.
    \fB-h, --help\fR            show this help message and exit
    \fB-pPORT, --port=PORT\fR   Set the TCP port (default: 8022)
    \fB-cCMD, --command=CMD\fR  set the command (default: /bin/login or ssh localhost)
    \fB-l, --log\fR             log requests to stderr (default: quiet mode)

.SH AUTHOR
Florent Gallaire <fgallaire@gmail.com>

This manual page was written for the Debian system by
Julien Valroff <julien@kirya.net> (but may be used by others).

.SH "REPORTING BUGS"
https://github.com/fgallaire/achilterm

.SH COPYRIGHT
Copyright (C) 2013 Florent Gallaire <fgallaire@gmail.com>
.br
Copyright (C) 2006 Antony Lesuisse <al@udev.org>
