.TH achilterm "1" "August 2016" "achilterm 0.18" "User commands"
.SH NAME
Achilterm \- Web based terminal written in python

.SH DESCRITPION
\fBAchilterm\fR is a lightweight \fB\UTF-8\fR web based terminal written in python and some AJAX
javascript for client side.
.br
Achilterm support Python 2.5 and above and Python 3.2 and above.
.br
It can use almost any web browser and even works through firewalls.

.SH USAGE
\fBachilterm\fR [options]

.SH OPTIONS
A summary of the options supported by \fBachilterm\fR is included below:
    \fB-h, --help\fR            show this help message and exit
    \fB-pPORT, --port=PORT\fR   Set the TCP port (default: 8022)
    \fB-cCMD, --command=CMD\fR  set the command (default: /bin/login or ssh localhost)
    \fB-l, --log\fR             log requests to stderr (default: quiet mode)
    \fB-L, --lite\fR            use Achiltermlite

.SH AUTHOR
Florent Gallaire <fgallaire@gmail.com>
.br
Antony Lesuisse <al@udev.org>
.br
Julien Valroff <julien@kirya.net>

.SH "REPORTING BUGS"
https://github.com/fgallaire/achilterm

.SH COPYRIGHT
Copyright (C) 2013-2016 Florent Gallaire <fgallaire@gmail.com>
.br
Copyright (C) 2006 Antony Lesuisse <al@udev.org>
